/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Feistel */

#ifndef _Included_Feistel
#define _Included_Feistel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Feistel
 * Method:    encryptSignal
 * Signature: ([B[I)V
 */
JNIEXPORT void JNICALL Java_Feistel_encryptSignal
  (JNIEnv *, jclass, jbyteArray, jintArray);

/*
 * Class:     Feistel
 * Method:    decryptSignal
 * Signature: ([B[I)V
 */
JNIEXPORT void JNICALL Java_Feistel_decryptSignal
  (JNIEnv *, jclass, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
